### ISSUE TITLE
Error during the compilation

### ISSUE THREAD

**Issue by alexandreborges** [guedou/r2m2#32]
Dear developers,

Good morning. How are you?

Unfortunately, I haven't gotten correctly compiling the r2m2  as shown below:

root@ubuntu1:~/r2m2# **make all install**

python tools/gen_includes.py /usr/include/libr
python tools/cffi_miasm.py r2m2_ad
Traceback (most recent call last):
  File "tools/cffi_miasm.py", line 31, in <module>
    ffi.embedding_api(includes)
  File "/usr/local/lib/python2.7/dist-packages/cffi/api.py", line 110, in embedding_api
    self._cdef(csource, packed=packed, dllexport=True)
  File "/usr/local/lib/python2.7/dist-packages/cffi/api.py", line 121, in _cdef
    self._parser.parse(csource, override=override, **options)
  File "/usr/local/lib/python2.7/dist-packages/cffi/cparser.py", line 315, in parse
    self._internal_parse(csource)
  File "/usr/local/lib/python2.7/dist-packages/cffi/cparser.py", line 320, in _internal_parse
    ast, macros, csource = self._parse(csource)
  File "/usr/local/lib/python2.7/dist-packages/cffi/cparser.py", line 278, in _parse
    self.convert_pycparser_error(e, csource)
  File "/usr/local/lib/python2.7/dist-packages/cffi/cparser.py", line 307, in convert_pycparser_error
    **raise CDefError(msg)
cffi.error.CDefError: cannot parse "RBuffer *buf_inc;"
<cdef source string>:14:2: before: RBuffer
Makefile:47: recipe for target 'miasm_embedded_r2m2_ad.c' failed
make: *** [miasm_embedded_r2m2_ad.c] Error 1**

This error occurs using **Ubuntu 16.04.1 and Kali Linux 2018**. The same error also happen when I tried do build the docker using "**docker build -t guedou/r2m2  .**".  All requirements (radare2, miasm, cffi, pycparser and jinja2) are installed. 

Additionally, I've tried changing the  cffi and pycparser versions, but I've gotten the same error.

I hope you have an amazing day. 

Alexandre.

**Comment by guedou** [comment]
Thanks for reporting the issue. Your bug is likely related to the fact that r2m2 is not compatible with radare2 >= 1.6.0. I am planning to update it in June or July depending on my schedule.

In the meantime, I will suggest that you use the pre-build docker image https://github.com/guedou/r2m2#testing-r2m2

**Comment by guedou** [comment]
PR #33 fixes your issue. It adds support for radare2 2.6.0 and the latest miasm.

**Comment by alexandreborges** [comment]
Thank you for updating it, Guillaume. 

I'Il check it. 

Have an amazing day.

Alexandre.

**Comment by guedou** [comment]
Fixed by #33. The corresponding docker image will be available soon.
