### ISSUE TITLE
r2m2 arch not present yet

### ISSUE THREAD

**Issue by gogo2464** [guedou/r2m2#40]
docker run -v "$(pwd)":/home/r2m2 --rm -it -e 'R2M2_ARCH=x86_64' guedou/r2m2 bash

[r2m2@90280a71d3a6 ~]$ rasm2 -L | grep r2m2
[r2m2@90280a71d3a6 ~]$

**Comment by gogo2464** [comment]
but 

```powershell
> docker run --rm -it -e 'R2M2_ARCH=x86_64' guedou/r2m2
 -- Pass '-j' to rabin2 to get the information of the binary in JSON format.
[0x00000000]> e anal.arch=? | grep r2m2
r2m2
[0x00000000]>```

this command works!!

just need to document more maybe

**Comment by guedou** [comment]
All r2m2 code is located in /home/r2m2. Your bind mount overrides r2m2 code and therefore makes the command fail.

**Comment by gogo2464** [comment]
yes my bad. sorry :)
