### ISSUE TITLE
tell in the doc if the win32 api is supported

### ISSUE THREAD

**Issue by gogo2464** [guedou/r2m2#41]
I was using r2m2 because I was looking for a tool to emulate PEB and win32 api from r2 command line.

Does r2m2 answer to my issue? Is it implemented?

best regards.

**Comment by guedou** [comment]
Thanks for your interest in r2m2. This project is somehow unmaintained and depends on outdated versions of radare2 and miasm. It will therefore suggest that you have a look at these projects instead.
